### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by DennisYurichev** [marekpiotrow/UWrMaxSat#5]
Marek,

The following code must work:

```
        void* ctx=ipamir_init();
        ipamir_add_hard(ctx, 1);
        ipamir_add_hard(ctx, -2);
        ipamir_add_hard(ctx, 3);
        ipamir_add_hard(ctx, 0);
        //ipamir_add_soft_lit (ctx, 4, 1000); // absent here!
        ipamir_solve(ctx);
        ipamir_release(ctx);
```

But instead it crashes...

```
i@Rocinante ~/tmp/ipamir % gdb ./must_work
...
(gdb) run
Starting program: /home/i/tmp/ipamir/must_work
...
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff71d6ce2 in PbSolver::setupOccurs() () from ./libuwrmaxsat.so.1
(gdb) info stack
#0  0x00007ffff71d6ce2 in PbSolver::setupOccurs() () from ./libuwrmaxsat.so.1
#1  0x00007ffff71d723d in PbSolver::propagate() () from ./libuwrmaxsat.so.1
#2  0x00007ffff71dc8a1 in PbSolver::solve(PbSolver::solve_Command) () from ./libuwrmaxsat.so.1
#3  0x00007ffff71b4bf2 in ipamir_solve () from ./libuwrmaxsat.so.1
#4  0x0000555555555213 in main () at must_work.c:13
(gdb)
```

But when I add soft literal(s), all works.
I'm not an expert in MaxSAT. But I believe, MaxSAT solver must work with only hard clauses present in instance?

Secondly, memory leaks.

See mem_leak_test.c.
Run it with, say "ulimit -Sv 1000000", it will exits silently.
However, Valgrind doesn't show any interesting info.
Run it with bigger ulimit, and you'll see in htop how memory consumption is (quickly) growing.

All the files I used:
https://yurichev.com/tmp2/UWrMaxSat_bugs.tar

TIA!

Thanks for your work on MaxSAT!

**Comment by DennisYurichev** [comment]
Follow-up.
If compiled statically against .a libraries, Valgrind can show something.

```
i@Rocinante ~/tmp/ipamir % valgrind --leak-check=full --show-leak-kinds=all ./mem_leak_test2
...
==64890== Command: ./mem_leak_test2
==64890==
i 0
==64890==
==64890== HEAP SUMMARY:
==64890==     in use at exit: 8,305,808 bytes in 363 blocks
==64890==   total heap usage: 845,565 allocs, 845,202 frees, 694,890,148 bytes allocated
==64890==
==64890== 800 bytes in 100 blocks are indirectly lost in loss record 1 of 5
==64890==    at 0x48487A9: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==64890==    by 0x12CFB3: COMinisatPS::vec<COMinisatPS::Lit>::capacity(int) (in /home/i/tmp/ipamir/mem_leak_tes
t2)
==64890==    by 0x12BA88: ipamir_solve (in /home/i/tmp/ipamir/mem_leak_test2)
==64890==    by 0x12A36F: main (mem_leak_test2.c:15)
```

Maybe this an issue.

**Comment by DennisYurichev** [comment]
BTW, the very same 'bug' I found today in another maxsat solver:

```
 % ./tt-open-wbo-inc-Glucose4_1_static
c
c TT-Open-WBO-Inc:       an Anytime MaxSAT Solver -- based on Glucose4_1 (core version)
c Version:       MaxSAT Evaluation 2022
c Author:        Alexander Nadel
```
It crashes if WCNF without soft clauses applied.
But Open-WBO works.

**Comment by marekpiotrow** [comment]
Hi Dennis,

A have just pushed a fix the the bugs described above. I hope it solves the problems.

Marek

**Comment by DennisYurichev** [comment]
Thanks!
